name = "key-onl"
main = "worker.js"
compatibility_date = "2024-11-01"

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "Lobby"

[[durable_objects.bindings]]
name = "MATCH"
class_name = "Match"

[[durable_objects.bindings]]
name = "RANKING"
class_name = "Ranking"

[[durable_objects.bindings]]
name = "ADMIN_AUTH"
class_name = "AdminAuth"

[[durable_objects.bindings]]
name = "USER_AUTH"
class_name = "UserAuth"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Lobby", "Match"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Ranking"]

[[migrations]]
tag = "v3"
new_sqlite_classes = ["AdminAuth"]

[[migrations]]
tag = "v4"
new_sqlite_classes = ["UserAuth"]

[vars]
GOOGLE_CLIENT_ID = "7365893755-eqm3coij6otohorig4bgq4mtoen1q7sf.apps.googleusercontent.com"
